import { Router } from 'express';
import brand from './brand';
import company from './company';
import staff from './staff';    
import group from './group';
import chat from './chat';
import upload from './upload';
import media from './media';
import task from './task';
const admin: Router = Router();

admin.use('/brand', brand);
admin.use('/company', company);
admin.use('/staff', staff);
admin.use('/group', group);
admin.use('/chat', chat);
admin.use('/upload', upload);
admin.use('/task', task);
admin.use('/media', media);
export default admin;
